import "./globals.scss";
import styles from "./layout.module.scss";
import localFont from "next/font/local";
import { Archivo_Narrow } from "next/font/google";
import type { Metadata } from "next";

 
const archivoNarrow = Archivo_Narrow();
 
const canter = localFont({
  src: "../public/fonts/canter.otf"
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={canter.className + " " + archivoNarrow.className}>
      <body className={styles.body}>
        {children}
      </body>
    </html>
  );
}
