import "./globals.scss";
import styles from "./layout.module.scss";
import { Open_Sans } from "next/font/google";
import type { Metadata } from "next";

const openSans = Open_Sans();

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={openSans.className}>
      <body className={styles.body}>
        {children}
      </body>
    </html>
  );
}
